import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


import {
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from '@chakra-ui/react'

import { Heading } from '@chakra-ui/react'
import { Text } from '@chakra-ui/react'
import { Flex, Spacer } from '@chakra-ui/react'
import { Container } from '@chakra-ui/react'
import Cabezal from '../components/Cabezal'


export default function Home() {
  return (
    <div>
      <Head>
        <title>SCFO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<Heading>
          To do Desarrollo de software senati
        </Heading>
        <Text>
          TODO, trabajos y documentos del area de desarrollo de software de senati
        </Text>
        <Cabezal />

<Container>
  There are many benefits to a joint design and development system. Not only
  does it bring benefits to the design team, but it also brings benefits to
  engineering teams. It makes sure that our experiences have a consistent look
  and feel, not just in our design specs, but in production
</Container>





{/* footer */}

    </div>
  )
}
